spring.application.name=Gestao de custo pessoais

# ===============================
# CONFIGURAÇÃO DO BANCO
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/controle_de_custo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Cansado
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA PADRÃO
# ===============================
spring.jpa.hibernate.ddl-auto=update

# ===============================
# PROFILE ATIVO
# ===============================
# spring.profiles.active=perfomance
